### ISSUE TITLE
Environment Setup Help

### ISSUE THREAD

**Issue by stramuchak** [dfirtrack/dfirtrack#48]
I am in a digital forensics course this semester and was assigned the dfirtrack tool as a presentation topic. I'm required to give a demonstration of the tool; however, I'm having quite the trouble getting my environment setup correctly. I couldn't find any sort of contact information for the project contributors so I was hoping I could get in touch with someone who could help me out through here. 

@stuhli Thanks!
stramuchak@gmail.com

**Comment by stuhli** [comment]
Hi @stramuchak 

sorry for answering that late but for some reason I overlooked this question four days in a row (thx @n3x77 for giving a hint). :wink:

Can you give a brief description what you're struggling with? The [DFIRTrack ansible role / playbook](https://github.com/stuhli/dfirtrack_ansible) should still work as desired. Have you tried it?

Have you tried the basic development installation as described here in the [wiki](https://github.com/stuhli/dfirtrack/wiki/Installation)? Then you have to take the `settings.py` from the corresponding [ansible role](https://github.com/stuhli/dfirtrack_ansible) and change the relevant stuff (everything between curly brackets "{{...}}"), but I guess this is more way more challanging because the description is still incomplete. Especially as you have to switch back to default SQLite database (not a fact that I'm happy with but I still had no time to change this)...

So tell me how far you are and I'm going to help you out and by the way I'm going to fix the documentation. :smiley:
Greetings to AL!

**Comment by stramuchak** [comment]
I finally got it working yesterday afternoon actually, so no worries. I was using the ansible playbook the the issues where popping up with django when trying to run the createsuperuser and run_dfirtrack commands. I just ran into some permissions issues with some of the files they where using. 

After I got the tool up and running, I navigated to localhost:8000 and the page loaded with text only (no styling, images, background, etc.) I was running this in an ubuntu VM but today I am going to set it up on using the linux subsystem for windows and see if that changes anything.

**Comment by stuhli** [comment]
Glad to hear that you got it running!

The issue you experienced running DFIRTrack without styling using development server can be fixed by setting `DEBUG = True` within `dfirtrack/settings.py`, I guess.

**Comment by stramuchak** [comment]
That flag was already set and I still haven't been able to solve the issue :/

**Comment by stuhli** [comment]
Do you run the development server "plain" (as described in the wiki) or with docker? Unfortunately I can not say anything about the status of the docker role at the moment, because this was the work of a colleague of mine.

Another dumb question: did you allow Javascript in your browser?

But I recently updated the ansible role and playbook two days ago. They should work now for Ubuntu 16.04 / 18.04 and Debian Stretch. You should try them with a freshly installed VM of any of those distributions.

**Comment by stuhli** [comment]
Another point you should check:i guess your webserver is running in the context of `www-data`? Are there the right permissions under `/var/www/html/static` for this user to enter the directory and read the files? Are there static files (CSS, JS) in there at all?

This is especially because you mentioned some permission issues before...

**Comment by stramuchak** [comment]
I've performed a fresh install with a new Ubuntu 16.04 VM and still having the same issues. The static files are in the /var/www/html/static directory and I've even elevated the permissions to ensure that I can access them. 

I've inspected the requests via the chrome networking console and noticed that the requests are not failing or returning any errors (they aren't returning anything really). I'm wondering if I have the root directory setup wrong or something.... anyways, I can work without the styling if I have to. 

I am attempting to setup some "test data" for the presentation and was wondering if you had any suggestions or examples I could use as a basis for my model... like an example scenario that someone would use the tool for. 

Thanks for all the help!

**Comment by n3x77** [comment]
> I am attempting to setup some "test data" for the presentation and was wondering if you had any suggestions or examples I could use as a basis for my model... like an example scenario that someone would use the tool for.
> 
Hi, in general DFIRTrack was developed with the focus of tracking typical incident response activities and especially investigation steps during the analysis of and Advanced Persistence Threat (APT) attack. For illustration reasons you could possible use the famous APT1 Report created by Mandiant (see [APT1-Report](https://www.fireeye.com/content/dam/fireeye-www/services/pdfs/mandiant-apt1-report.pdf) or The analysis of the Grizzly Steppe attack (see [AR-17-20045)](https://www.us-cert.gov/sites/default/files/publications/AR-17-20045_Enhanced_Analysis_of_GRIZZLY_STEPPE_Activity.pdf) especially the kill chain section. 

Typical use cases for DFIRTrack in such incidents is:
1.) You have a huge list of server and client systems (without information of the system owner and the status of infection) --> So you can create systems and add the metadata like (Business Unit, Location, Ip address, Status of the system)
2.) You want to analyze a specials system so you could create tasks for that:
    * Request forensic image of the system
    * Start analysis of the system
    * Create Documentation of the system
3.) After you have identified some infected systems and generated some IoCs to look for you can create tasks like:
    * Check SystemA,B and C for new IoCs
    * Update Documentation for System A and B
4.) Add Timeline events to a special system (Timeline events are things like attacker activity on the host):
    * 2019-01-01  First connection of suspicious account
    * 2019-01-02 Installation of webshell
     *2019-01-04 Credential Dumping
     *2019-01-04 Possible Lateral movement from DMZ to internal network
    
If you add some example systems, tasks and timeline events, DFIRTrack will automatically generate a MKDocs Documentation of the current investigation. You can also create several exports like system spreadsheets, etc.

I hope this few examples can help you during the creation of testdata. If you need further techincal indicators you could also check the [MITRE ATT&CK Matrix](https://attack.mitre.org/).

@stuhli maybe we should create some example data and export the SQL-Database so that new users have some hints how to use DFIRTrack.

**Comment by stuhli** [comment]
@stramuchak 
To help you with the styling I need you to answer the following questions:

- Did you use Ansible?
- Do you run the development or productive server?
- May you show me the some permissions by executing the following commands (maybe you have to install `tree` first): `cd /var/www && tree -dpug`
- What is the content of the following variables `DEBUG`, `STATIC_URL` and `STATIC_ROOT` in `dfirtrack/settings.py`?

@n3x77 (and @stramuchak)
That's a good idea. I am going to do this until the end of this week. I am going to add some data for use with importers and creators too.

**Comment by stuhli** [comment]
I added a test database to **develop** branch.

[Here](https://github.com/stuhli/dfirtrack/wiki/Example-data#database-with-example-case-data) is a brief description for importing it.

**Comment by stramuchak** [comment]
Thanks for the help, we had the presentation last week and it went great.
